# $FreeBSD$

# This is a place to put directory creation for some things that do not
# have an obvious home, and just need to be created.
# Please keep this sorted by path.

DIRS+=	ETC_X11
ETC_X11=	/etc/X11

SYMLINKS+=	usr/src/sys /sys

DIRS+=	TMP
TMP=	/tmp
TMP_MODE=	1777

.include <bsd.prog.mk>
