# $FreeBSD$

PACKAGE=runtime

CONFS=          bootmisc fsck ipfw ldconfig localmount moused netmount powerd rarpd \
		savecore staticroute swap syscons tmpfiles urandom

NO_OBJ=
CONFSDIR=       /etc/conf.d
CONFSMODE=      755

.include <bsd.prog.mk>

