#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: mail
# REQUIRE: LOGIN

# XXX - TEMPORARY SCRIPT UNTIL YOU WRITE YOUR OWN REPLACEMENT.
#
. /etc/rc.subr

load_rc_config

if [ -n "${mta_start_script}" ]; then
	[ "${mta_start_script}" != "/usr/libexec/sendmail/rc.sendmail" ] && \
	    sh ${mta_start_script} "$1"
fi
