# $FreeBSD$

SUBDIR=	common_source .WAIT \
	chkprintcap lp lpc lpd lpq lpr lprm lptest pac \
	syslog.d \
	filters filters.ru
SUBDIR_PARALLEL=

# Questions/ideas for lpr & friends could also be sent to:
#	freebsd-print@bostonradio.org

.include <bsd.subdir.mk>
